exp_name: sac_lr_1
model: sac
env_name: bertrand
use_lstm: False
n_actions: 1
variation: base

env: # environment params
  N: 2
  k: 1
  v: 3
  rho: 0.0002
  xi: 0.2
  inflation_start: 0

agent: # agent params
  actor_lr: 0.0005
  Q_lr: 0.0005
  alpha_lr: 0.0005
  gamma: 0.95
  tau: 0.01
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 200_000

train: # train params
  episodes: 1
  timesteps: 250_000
  update_steps: 1
  deviate_start: 0.85
  deviate_end: 0.95