exp_name: dqn_k_2
model: dqn
env_name: bertrand
n_actions: 15
variation: base
random_state: 3381

env: # environment params
  N: 2
  k: 25
  v: 30
  rho: 0.001
  inflation_start: 0

agent: # agent params
  lr: 0.1
  gamma: 0.95
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 200_000

train: # train params
  episodes: 1
  timesteps: 250_000
  update_steps: 1
  deviate_start: 0.85
  deviate_end: 0.95
  test_size: 0.33