exp_name: dqn_base
model: dqn
env_name: bertrand
n_actions: 15
variation: base
random_state: 3381

env: # environment params
  N: 2
  k: 1
  v: 3
  rho: 0.001
  inflation_start: 0

agent: # agent params
  lr: 0.01
  gamma: 0.95
  hidden_size: 256

buffer: # buffer params
  sample_size: 256
  buffer_size: 20_000

train: # train params
  episodes: 1
  timesteps: 400_000
  update_steps: 1
  deviate_step: 350_000
  test_size: 0.33
