exp_name: dqn_k_1
model: dqn
env_name: linear
use_lstm: False
n_actions: 15
variation: base
random_state: 3380

env: # environment params
  N: 2
  k: 10
  v: 12
  rho: 0.0002
  inflation_start: 0

agent: # agent params
  lr: 0.1
  gamma: 0.95
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 200_000

train: # train params
  episodes: 1
  timesteps: 250_000
  update_steps: 1
  deviate_start: 0.85
  deviate_end: 0.95