exp_name: sac_k_2
model: sac
env_name: linear
use_lstm: False
n_actions: 1
variation: base

env: # environment params
  N: 2
  k: 25
  v: 30
  rho: 0.0002
  xi: 0.2
  inflation_start: 0

agent: # agent params
  actor_lr: 0.0001
  Q_lr: 0.0001
  alpha_lr: 0.0001
  gamma: 0.95
  tau: 0.01
  hidden_size: 256

buffer: # buffer params
  sample_size: 512
  buffer_size: 100_000

train: # train params
  episodes: 1
  timesteps: 200_000
  update_steps: 1
  deviate_start: 0.85
  deviate_end: 0.95