# list of countries to filter
countries = [
    'Switzerland',
    'Japan',
    'Germany',
    'Singapore',
    'Canada',
    'Australia',
    'Netherlands',
    'Finland',
    'Norway',
    'Sweden',
    'Luxembourg',
    'Austria',
    'Belgium',
    'Denmark',
    'United States',
    'United Kingdom',
    'New Zealand',
    'South Korea',
    'France',
    'Italy',
    'Hong Kong',
    'Israel',
    'Ireland',
    'Taiwan',
    'Spain',
    'Cyprus',
    'Portugal',
    'Greece',
    'Slovenia',
    'Estonia',
    'Czech Republic',
    'Malta',
    'Slovakia',
    'Poland',
    'Hungary',
    'Latvia',
    'Lithuania',
    'Iceland',
    'Chile',
    'Costa Rica',
    'Bermuda',
    'Qatar',
    'Bahrain',
    'United Arab Emirates',
    'Saudi Arabia',
    'Kuwait',
    'Oman',
    'Macao',
    'China',
    'Thailand'
]
